apiVersion: sources.knative.dev/v1alpha1
kind: PingSource
metadata:
  name: test-ping-source
spec:
  schedule: "* * * * *"
  data: '{"message": "Hello World Ping"}'
  sink:
   ref:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Broker
    name: default
