apiVersion: sources.eventing.knative.dev/v1alpha1
kind: CronJobSource
metadata:
  name: eventinghello-cronjob-source
spec:
  schedule: "* * * * *"
  data: '{"key": "every min"}'
  sink:
    ref:
      apiVersion: messaging.knative.dev/v1alpha1
      kind: Channel
      name: eventinghello-ch
